1451451746920	Sync.ErrorHandler	DEBUG	Flushing file log.
1451451746922	Sync.Service	DEBUG	Exception: [object Object] No traceback available
1451451746922	Sync.Service	DEBUG	Not syncing: login returned false.
1451451746923	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451451746923	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451451746923	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451451746924	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451451746924	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451451746924	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451451746927	Sync.ErrorHandler	DEBUG	Log cleanup threshold time: 1450587746927
1451451746928	Sync.ErrorHandler	DEBUG	No logs to clean up.
1451451746929	Sync.ErrorHandler	DEBUG	Log cleanup threshold time: 1450587746929
1451451746930	Sync.ErrorHandler	DEBUG	No logs to clean up.
1451452346920	Sync.Service	DEBUG	User-Agent: Iceweasel/31.8.0 FxSync/1.33.0.20150701023259.
1451452346921	Sync.Service	INFO	Starting sync at 2015-12-30 00:12:26
1451452346922	Sync.Service	DEBUG	In sync: should login.
1451452346923	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451452346923	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451452346923	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451452346924	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451452346924	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451452346924	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451452346929	Sync.BrowserIDManager	INFO	Waiting for user to be verified.
1451452346930	FirefoxAccounts	DEBUG	already verified
1451452346931	Sync.BrowserIDManager	INFO	Starting fetch for key bundle.
1451452346932	Sync.BrowserIDManager	INFO	Fetching assertion and token from: https://token.services.mozilla.com/1.0/sync/1.5
1451452346932	FirefoxAccounts	DEBUG	already verified
1451452346932	Sync.BrowserIDManager	DEBUG	Getting an assertion
1451452346932	FirefoxAccounts	DEBUG	enter getAssertion()
1451452346934	FirefoxAccounts	DEBUG	getKeyPair: already have a keyPair
1451452346935	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1451452425728	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451452445687	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451452459042	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 620"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:620 < _onComplete()@resource://services-common/hawkclient.js:156 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459044	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 636"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:636 < _onComplete()@resource://services-common/hawkclient.js:159 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459045	FirefoxAccounts	DEBUG	(Response) /certificate/sign: code: null - Status text: null
1451452459047	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 670"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:670 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:247 < _onComplete()@resource://services-common/hawkclient.js:166 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459048	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 670"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:670 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:247 < _onComplete()@resource://services-common/hawkclient.js:167 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459050	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 636"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:636 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:71 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459051	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 620"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:620 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:72 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459053	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 620"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:620 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:73 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459054	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 670"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:670 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:75 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451452459058	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"error":{},"message":null,"code":null,"errno":null}
1451452459059	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"error":{},"message":null,"code":null,"errno":null}
1451452459061	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: null
1451452459061	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451452459061	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451452459061	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1451452459062	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms.
