1451451034743	Sync.ErrorHandler	DEBUG	Flushing file log.
1451451034744	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: [object Object]
1451451034744	Sync.BrowserIDManager	ERROR	Could not authenticate: [object Object]
1451451034745	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451451034745	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451451034745	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451451034745	Sync.ErrorHandler	DEBUG	Log cleanup threshold time: 1450587034745
1451451034746	Sync.ErrorHandler	DEBUG	No logs to clean up.
1451451038729	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451451038729	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451451038730	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451451052098	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451164115	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451169525	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451170951	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451176251	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451205371	Sync.Tracker.Forms	DEBUG	Saving changed IDs to forms
1451451205616	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451212056	Sync.Tracker.Forms	DEBUG	Saving changed IDs to forms
1451451212229	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451213556	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451214974	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451244488	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451249500	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451263902	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451278362	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451286376	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451289626	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451511644	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1451451634744	Sync.Service	DEBUG	User-Agent: Iceweasel/31.8.0 FxSync/1.33.0.20150701023259.
1451451634744	Sync.Service	INFO	Starting sync at 2015-12-30 00:00:34
1451451634745	Sync.Service	DEBUG	In sync: should login.
1451451634746	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451451634747	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451451634747	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451451634747	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1451451634747	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451451634747	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451451634760	Sync.BrowserIDManager	INFO	Waiting for user to be verified.
1451451634760	FirefoxAccounts	DEBUG	already verified
1451451634762	Sync.BrowserIDManager	INFO	Starting fetch for key bundle.
1451451634762	Sync.BrowserIDManager	INFO	Fetching assertion and token from: https://token.services.mozilla.com/1.0/sync/1.5
1451451634762	FirefoxAccounts	DEBUG	already verified
1451451634763	Sync.BrowserIDManager	DEBUG	Getting an assertion
1451451634763	FirefoxAccounts	DEBUG	enter getAssertion()
1451451634773	FirefoxAccounts	DEBUG	getKeyPair: already have a keyPair
1451451634773	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1451451746892	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 620"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:620 < _onComplete()@resource://services-common/hawkclient.js:156 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746894	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 636"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:636 < _onComplete()@resource://services-common/hawkclient.js:159 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746895	FirefoxAccounts	DEBUG	(Response) /certificate/sign: code: null - Status text: null
1451451746897	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 670"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:670 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:247 < _onComplete()@resource://services-common/hawkclient.js:166 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746899	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 670"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:670 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:247 < _onComplete()@resource://services-common/hawkclient.js:167 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746901	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 636"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:636 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:71 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746902	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 620"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:620 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:72 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746904	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 620"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:620 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:73 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746905	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 670"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:670 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:75 < _onComplete()@resource://services-common/hawkclient.js:172 < onComplete()@resource://services-common/hawkclient.js:213 < onStopRequest()@resource://services-common/rest.js:444 < waitForSyncCallback()@resource://services-common/async.js:99 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:141 < onNotify()@resource://gre/modules/services-sync/service.js:963 < WrappedNotify()@resource://services-sync/util.js:141 < WrappedLock()@resource://services-sync/util.js:96 < WrappedCatch()@resource://services-sync/util.js:70 < login()@resource://gre/modules/services-sync/service.js:985 < sync/<()@resource://gre/modules/services-sync/service.js:1231 < WrappedCatch()@resource://services-sync/util.js:70 < sync()@resource://gre/modules/services-sync/service.js:1227 < <file:unknown>
1451451746908	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"error":{},"message":null,"code":null,"errno":null}
1451451746909	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"error":{},"message":null,"code":null,"errno":null}
1451451746910	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: null
1451451746911	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1451451746911	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1451451746911	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1451451746912	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms.
